### PR TITLE
conexon connect issue #451

### PR DESCRIPTION
**Pull request by megan-conexon**
@feomike This PR is ready for review. Let me know if there is anything that I can add.

cc: @awolfe76 since he helped me out on the click event

### CODE REVIEW

**Comment by feomike** [comment]
good demo - checks out with initial requirements - nice work.  was it fun @megan-conexon ?

**Comment by megan-conexon** [comment]
@feomike merging

yes, this was fun!

**Comment by awolfe76** [comment]
Late to this one 🙏 . Really cool @megan-conexon! 

Just so anyone that has access can take a quick look, https://conexon.github.io/coop/demo/conexon_connect.html.

@feomike - Let me know if we want to put this up on `conexonmaps` in some way too.

**Comment by feomike** [comment]
@awolfe76 - nope, we are keeping this as demo - likely for a while.  meeting w/ marketing to understand more about requirements tomorrow.  more details (other issues) to follow. 

and 👏 to @megan-conexon for first public map push

**Pull request merged**
