### PR TITLE
initial commit

### PR DESCRIPTION
**Pull request by feomike**
updated notes
-------------
- all geojson (point) state files were updated
- the below `client_geoid.json` and `client_sub.geojson` files have all been updated, and need to be tested
- testing should 
  - confirm that selection of substaitons and blockgroups works as expected
  - confirm that when select all, the sum of the numbers matches those in the updated spreadsheet found  here - https://docs.google.com/spreadsheets/d/1tO0rYffTV3Go7cN85gUgxIJ9gil6LfjJb6IvDjRnbbA/edit#gid=165658630 - the `coop_meter_range` worksheet
- only CO and NY state tiles have been updated

list of coops so far
- [ ] AR,Ashley_Chicot_Electric_Cooperative,ACEC - `not enough data for map 2 yet`
- [ ] AR,Farmers_Electric_Cooperative,FARMERS - `not enough data for map 2 yet`
- [ ] AR,First_Electric_Cooperative,FIRST - `index not selecting all bgs`
- [x] AR,Mississippi_County_Electric,MCECI - `index not selecting all bgs`
- [x] AR,North_Arkansas_Electric_Cooperative,NORTHAR - `green block only on both work; any on both fail`
- [x] AR,OzarksGo,OZARKSGO - `multi-state not prepared yet`
- [x] AR,Petit_Jean_Electric_Cooperative,PETITJEAN - `both wrong in both maps`
- [x] AR,South_Central_Arkansas_Electric_Cooperative,SCAEC - `green only on both works; any method on both fails`
- [ ] AR,Woodruff_Electric_Cooperative_Corporation,WECC - `block groups green works, others fail`
- [x] CO,Delta_Montrose_Electric_Association,DMEA
- [ ] CO,Holy_Cross_Energy,HOLYCROSS - `not enough data for map 2 yet`
- [x] CO,Yampa_Valley_Electric_Association,YVEA
- [x] GA,Central_Georgia_Electric_Membership_Corporation,CGEMC - `both numbers don't match`
- [x] GA,Irwin_Electric_Membership_Cooperative,IEMC - `green only matches`
- [x] GA,Middle_Georgia_Electric_Membership_Cooperative,MGEMC
- [x] GA,Satilla_Rural_Electric_Membership_Coorporation,SREMC
- [x] GA,Southern_Rivers_Energy,SRE
- [x] GA,Tri_County_Electric_Membership_Corporation,TRICNTGA
- [x] IL,Corn_Belt_Energy_Corporation,CORNBELT
- [x] IL,Shelby_Electric_Cooperative,SHELBYEC
- [x] KY,Kenergy,KEN
- [x] MD,Southern_Maryland_Electric_Cooperative,SMECO
- [x] MI,Great_Lakes_Energy_Electric_Cooperative,GREATLAKES
- [x] MI,HomeWorks_Tri_County_Electric_Cooperative,HWTCEC
- [x] MI,Midwest_Energy_Communications,MEC
- [x] MI,Presque_Isle_Electric_and_Gas_Cooperative,PIEG
- [x] MI,Thumb_Electric_Cooperative,THUMB
- [x] MO,Black_River_Electric_Cooperative,BREC
- [x] MO,Callaway_Electric_Cooperative,CALLAWAY
- [x] MO,Central_Missouri_Electric_Cooperative,CMEC
- [x] MO,Co_Mo_Electric,COMO
- [x] MO,Consolidated_Electric_Cooperative_Missouri,CONSOLMO
- [x] MO,Howell_Oregon_Electric_Cooperative,HOEC
- [x] MO,New_Mac_Electric_Cooperative,NEWMAC
- [x] MO,Osage_Valley_Electric_Cooperative,OSAGEVLY
- [x] MO,Ozarks_Electric_Cooperative,OZARKS
- [x] MO,Pemiscot_Dunklin,PEMDUNK
- [x] MO,Platte_Clay_Electric_Coop_Inc,PLATTE
- [x] MO,Sac_Osage_Electric_Cooperative,SACOSAGE
- [x] MO,SEMO_Electric_Cooperative,SEMO
- [x] MO,Three_Rivers_Electric_Cooperative,THREERIVERS
- [x] MO,United_Electric_Cooperative,UTD
- [x] MO,West_Central_Electric_Coop_Inc,WESTCEN
- [x] MS,Alcorn_County_Electric_Power_Association,ACEPA
- [x] MS,Central_Electric_Power_Association,CEPA
- [x] MS,Coahoma_Electric_Power_Association,COEPA
- [x] MS,Coast_Electric_Power_Association,COAST
- [x] MS,Delta_Electric_Power_Association,DELTA
- [x] MS,Dixie_Electric_Power_Association,DIXIEEPA
- [x] MS,East_Mississippi_Electric_Power_Association,EMEPA
- [x] MS,Monroe_County_Electric_Power_Association,MONROE
- [x] MS,Natchez_Trace_Electric_Power_Association,NTEPA
- [x] MS,Northcentral_Electric_Power_Association,NCEPA
- [x] MS,Northeast_Mississippi_Electric_Power_Association,NEMS
- [x] MS,Pearl_River_Valley_Electric_Power_Association,PRVEPA
- [x] MS,Prentiss_County_Electric_Power_Association,PCEPA
- [x] MS,Singing_River_Electric_Cooperative,SREC
- [x] MS,Southern_Pine_Electric,SOUPINE
- [x] MS,Tallahatchie_Valley_Electric_Power_Association,TVEPA
- [x] MS,Tippah_Electric_Power_Association,TPEPA
- [x] MS,Tishomingo_County_Electric_Power_Association,TCEPA
- [x] MS,Tombigbee_Electric_Power_Association,TOMBB
- [x] MS,Twin_County_Electric_Power_Association,TWINCOEPA
- [x] MS,Yazoo_Valley_Electric_Power_Association,YAZOO
- [x] NH,New_Hampshire_Electric_Cooperative,NHEC
- [x] NM,Kit_Carson_Electric_Cooperative,KCEC
- [x] NY,Otsego_Electric_Cooperative,OTSEGO

### CODE REVIEW

**Comment by feomike** [comment]
@awolfe76 - PR up; i'll start working from A, if you want to start working from N?

**Comment by awolfe76** [comment]
Just for tracking ...

`***` means holy💩   this looks weird.
`GOOD` means it all checks out.

```
NH,New_Hampshire_Electric_Cooperative,NHEC
spreadsheet 21,359,880 and 34,454,170
index 21,397,820.00 and 34,454,170.00
blockgroups 21,397,820.00 and 34,454,170.00

MS,Twin_County_Electric_Power_Association,TWINCOEPA
spreadsheet 26,558,500 and 34,089,770
index 26,558,500.00 and 36,720,740.00
blockgroups 26,558,500.00 and 36,720,740.00

MS,Tishomingo_County_Electric_Power_Association,TCEPA
map won't load, bad coopcode?

MS,Tippah_Electric_Power_Association,TPEPA
map won't load, bad coopcode?

MS,Tallahatchie_Valley_Electric_Power_Association,TVEPA
spreadsheet 39,368,420 and 58,664,120
index 39,385,960.00 and 58,664,120.00
blockgroups 39,385,960.00 and 58,664,120.00

MS,Southern_Pine_Electric,SOUPINE
spreadsheet 79,468,550 and 113,726,640
index 74,021,970.00 and 110,057,290.00
blockgroups 79,475,090.00 and 115,510,410.00

MS,Singing_River_Electric_Cooperative,SREC
spreadsheet 17,083,790 and 30,998,510
index 17,090,880.00 and 26,433,040.00
blockgroups 17,090,880.00 and 26,433,040.00

 MS,Prentiss_County_Electric_Power_Association,PCEPA
couldn't find PCEPA

 MS,Pearl_River_Valley_Electric_Power_Association,PRVEPA
spreasheet 49901090 and 71744870
index 48,923,690.00 and 70,690,790.00
blockgroups 49,977,770.00 and 71,744,870.00

MS,Northeast_Mississippi_Electric_Power_Association,NEMS
speradsheet 19924660 and 22596940
index 19,953,230.00 and 23,283,140.00
blockgroups 19,953,230.00 and 23,283,140.00

MS,Northcentral_Electric_Power_Association,NCEPA
not found

MS,Natchez_Trace_Electric_Power_Association,NTEPA
speradsheet 16,932,990 and 33,648,250
index 16,932,990.00 and 36,855,940.00
blockgroups 16,932,990.00 and 36,855,940.00

MS,Monroe_County_Electric_Power_Association,MONROE
not found

MS,East_Mississippi_Electric_Power_Association,EMEPA
spreadsheet 70,323,090 and 98,149,450
index 70,323,090.00 and 104,058,480.00
blockgroups 70,323,090.00 and 104,058,480.00

MS,Dixie_Electric_Power_Association,DIXIEEPA
spreadsheet 35,695,780 and 45,118,440
index 35,770,620.00 and 46,169,850.00
blockgroups 35,770,620.00 and 46,169,850.00

MS,Delta_Electric_Power_Association,DELTA
spreadsheet 75,034,000 and 127,242,280
index 76,111,070.00 and 129,702,150.00
blockgroups 76,111,070.00 and 129,702,150.00

MS,Coast_Electric_Power_Association,COAST
spreadsheet 18,922,290 and 27,143,900
index 18,923,460.00 and 27,143,900.00
blockgroups 18,923,460.00 and 27,143,900.00

*** MS,Coahoma_Electric_Power_Association,COEPA
spreadsheet 25,443,850 and 37,144,580
*** index 6,334,630.00 and 11,037,680.00
blockgroups 25,443,850.00 and 36,882,820.00

MS,Central_Electric_Power_Association,CEPA
spreadsheet 54,122,810 and 86,148,400
index 55,245,790.00 and 87,836,250.00
blockgroups 55,245,790.00 and 87,836,250.00

MS,Alcorn_County_Electric_Power_Association,ACEPA
spreadsheet 9,152,900 and 11,821,530
not found

MO,West_Central_Electric_Coop_Inc,WESTCEN
spreadsheet 56,908,480 and 89,695,040
index 56,908,480.00 and 93,030,350.00
blockgroups 56,908,480.00 and 93,030,350.00

*** MO,United_Electric_Cooperative,UTD
spreadsheet 10,487,580 and 34,572,390
*** index 5,809,900.00 and 28,482,530.00
*** blockgroups 5,809,900.00 and 28,482,530.00

*** MO,Three_Rivers_Electric_Cooperative,THREERIVERS
spreadsheet 50,243,270 and 69,259,090
*** index 209,444,080.00 and 276,753,040.00
blockgroups 52,361,020.00 and 69,259,090.00

GOOD - MO,SEMO_Electric_Cooperative,SEMO
spreadsheet 34,626,470 and 55,152,130
index 34,626,470.00 and 55,152,130.00
blockgroups 34,626,470.00 and 55,152,130.00

MO,Sac_Osage_Electric_Cooperative,SACOSAGE
spreadsheet 70,906,580 and 107,034,650
index 71,000,500.00 and 112,469,050.00
blockgroups 71,000,500.00 and 112,469,050.00

GOOD - MO,Platte_Clay_Electric_Coop_Inc,PLATTE
spreadsheet 34,184,350 and 48,031,740
index 34,184,350.00 and 48,031,740.00
blockgroups 34,184,350.00 and 48,031,740.00

MO,Pemiscot_Dunklin,PEMDUNK
spreadsheet 29,404,920 and 38,118,870
index 29,409,660.00 and 36,082,190.00
blockgroups 29,409,660.00 and 36,082,190.00

GOOD - MO,Ozarks_Electric_Cooperative,OZARKS
spreadsheet 6,836,090 and 14,265,430
index 6,836,090.00 and 14,265,430.00
blockgroups 6,836,090.00 and 14,265,430.00

MO,Osage_Valley_Electric_Cooperative,OSAGEVLY
spreadsheet 94,612,170 and 125,926,990
index 95,827,250.00 and 136,729,420.00
blockgroups 95,827,250.00 and 136,729,420.00

MO,New_Mac_Electric_Cooperative,NEWMAC
spreadsheet 3,455,470 and 106,038,160
not found

*** MO,Howell_Oregon_Electric_Cooperative,HOEC
spreadsheet 78,526,020 and 125,926,990
*** index 28,899,740.00 and 34,194,760.00
blockgroups 87,686,170.00 and 112,698,010.00

MO,Consolidated_Electric_Cooperative_Missouri,CONSOLMO
spreadsheet 13,440,630 and 25,211,770
index 13,709,200.00 and 26,631,740.00
blockgroups 13,709,200.00 and 26,631,740.00

MO,Co_Mo_Electric,COMO
spreadsheet 21,412,350 and 42,513,060
index 20,911,730.00 and 42,012,440.00
blockgroups 21,412,350.00 and 42,513,060.00

MO,Central_Missouri_Electric_Cooperative,CMEC
spreadsheet 52,036,120 and 71,728,570
index 49,979,350.00 and 69,162,830.00
blockgroups 52,629,490.00 and 71,812,970.00

MO,Callaway_Electric_Cooperative,CALLAWAY
spreadsheet 15,140 and 2,729,050
index 15,140.00 and 5,410,220.00
blockgroups 15,140.00 and 5,410,220.00

MO,Black_River_Electric_Cooperative,BREC
spreadsheet 89,500,450 and 127,831,000
index 84,217,790.00 and 122,548,340.00
blockgroups 89,500,450.00 and 127,831,000.00

MI,Thumb_Electric_Cooperative,THUMB
spreadsheet 24,695,760 and 106,380,780
not found

MI,Presque_Isle_Electric_and_Gas_Cooperative,PIEG
spreadsheet 74,082,070 and 94,527,250
index 74,186,300.00 and 98,556,810.00
blockgroups 74,186,300.00 and 98,556,810.00

MI,Midwest_Energy_Communications,MEC
spreadsheet 330,640 and 15,524,030
not found

MI,HomeWorks_Tri_County_Electric_Cooperative,HWTCEC
spreadsheet 583,710 and 6,519,070
index 629,880.00 and 6,519,070.00
blockgroups 629,880.00 and 6,519,070.00

MI,Great_Lakes_Energy_Electric_Cooperative,GREATLAKES
spreadsheet 84,718,100 and 150,050,910
index 87,030,520.00 and 150,063,370.00
blockgroups 87,030,520.00 and 150,063,370.00

MD,Southern_Maryland_Electric_Cooperative,SMECO
spreadsheet 12,112,680 and 13,032,220
index 12,628,790.00 and 13,251,820.00
blockgroups 12,628,790.00 and 13,251,820.00
```

**Comment by feomike** [comment]
nice icon; zero'ing in on this; will take a while to snuff out

**Comment by feomike** [comment]
@awolfe76 - made some progress, but slow going; a refresh to this PR is coming - likely not until tomorrow.

**Comment by awolfe76** [comment]
2nd round of testing, on `index.html` only.

`*` is where I see mismatches. That is 5/16 tested. The list of 5 is:

- MO,Howell_Oregon_Electric_Cooperative,HOEC
- MO,Black_River_Electric_Cooperative,BREC
- MO,Central_Missouri_Electric_Cooperative,CMEC
- (upper limit) IL,Corn_Belt_Energy_Corporation,CORNBELT
- AR,First_Electric_Cooperative,FIRST 

Missouri seems to be off in all cases (tested 3 of them for that reason).

```
NY,Otsego_Electric_Cooperative,OTSEGO
index
ui
18,925,410 and 11,732,200
spreadsheet
18,925,410 and 11,732,200

MS,Tombigbee_Electric_Power_Association,TOMBB
index
ui
29,462,100 and 12,471,080
spreadsheet
29,462,100 and 12,471,080

MS,Singing_River_Electric_Cooperative,SREC
index
ui
30,998,510 and 17,093,280
spreadsheet
30,998,510 and 17,093,280

MS,Coast_Electric_Power_Association,COAST
index
ui
27,143,900 and 18,923,460
spreadsheet
27,143,900 and 18,923,460

MO,New_Mac_Electric_Cooperative,NEWMAC
index
not found

**** MO,Howell_Oregon_Electric_Cooperative,HOEC
index
ui
34,553,730 and 28,899,740
spreadsheet
113,056,980 and 87,686,170

* MO,Black_River_Electric_Cooperative,BREC
index
ui
122,548,340 and 84,217,790
spreadsheet
127,831,000 and 89,500,450

MO,Central_Missouri_Electric_Cooperative,CMEC
index
ui
69,078,430 and 49,385,980
spreadsheet
71,728,570 and 52,036,120

MI,Presque_Isle_Electric_and_Gas_Cooperative,PIEG
index
ui
98,556,810 and 74,186,300
spreadsheet
98,556,810 and 74,186,300

MD,Southern_Maryland_Electric_Cooperative,SMECO
index
ui
13,032,220 and 12,400,950
spreadsheet
13,032,220 and 12,400,950

KY,Kenergy,KEN
index
ui
100,678,570 and 92,440,990
spreadsheet
100,678,570 and 92,440,990

* (upper limit) IL,Corn_Belt_Energy_Corporation,CORNBELT
index
ui
119,285,010 and 51,160,280
spreadsheet
119,748,260 and 51,160,280

IL,Shelby_Electric_Cooperative,SHELBYEC
index
ui
100,839,080 and 72,362,840
spreadsheet
100,839,080 and 72,362,840

GA,Middle_Georgia_Electric_Membership_Cooperative,MGEMC
index
ui
25,047,630 and 18,613,270
spreadsheet
25,047,630 and 18,613,270

CO,Yampa_Valley_Electric_Association,YVEA
index
ui
64,875,680 and 38,094,110
spreadsheet
64,875,680 and 38,094,110

AR,South_Central_Arkansas_Electric_Cooperative,SCAEC
index
ui
56,347,820 and 34,021,140
spreadsheet
56,347,820 and 34,021,140

* AR,First_Electric_Cooperative,FIRST 
index
ui
114,354,500 and 85,149,220
spreadsheet
129,426,660 and 94,136,890
```

**Pull request merged**
